"""Minimal ICC v2 writer: input-class RGB -> Lab profile with an A2B0
lut16Type ('mft2') tag. This is all darktable needs for a custom input
color profile (it goes through LittleCMS2 for LUT profiles).
"""
from __future__ import annotations

import struct
import numpy as np


def _s15f16(x):
    return int(round(x * 65536)) & 0xFFFFFFFF


def _desc_tag(text: str) -> bytes:
    ascii_ = text.encode('ascii', errors='replace') + b'\0'
    return (b'desc' + b'\0' * 4 + struct.pack('>I', len(ascii_)) + ascii_
            + struct.pack('>II', 0, 0)      # unicode lang code + count
            + struct.pack('>HB', 0, 0)      # scriptcode + count
            + b'\0' * 67)


def _text_tag(text: str) -> bytes:
    return b'text' + b'\0' * 4 + text.encode('ascii', errors='replace') + b'\0'


def _xyz_tag(xyz) -> bytes:
    return b'XYZ ' + b'\0' * 4 + struct.pack('>3I', *(_s15f16(v) for v in xyz))


def _mft2_tag(lab: np.ndarray, input_table: np.ndarray, grid: int) -> bytes:
    """lut16Type: identity matrix, shaper input tables, Lab16 legacy CLUT."""
    head = b'mft2' + b'\0' * 4 + struct.pack('>4B', 3, 3, grid, 0)
    ident = struct.pack('>9I', *(_s15f16(v) for v in
                                 (1, 0, 0, 0, 1, 0, 0, 0, 1)))
    n_in, n_out = len(input_table), 256
    counts = struct.pack('>HH', n_in, n_out)
    itab = np.clip(np.round(input_table * 65535), 0, 65535).astype('>u2')
    in_tables = itab.tobytes() * 3
    # ICC v2 legacy 16-bit Lab encoding: L* 0..100 -> 0..0xFF00,
    # a*/b* -128..+127 -> 0..0xFF00
    L = np.clip(lab[:, 0] * 652.80, 0, 65280)
    a = np.clip((lab[:, 1] + 128.0) * 256.0, 0, 65280)
    b = np.clip((lab[:, 2] + 128.0) * 256.0, 0, 65280)
    clut = np.stack([L, a, b], axis=-1)
    clut_b = np.round(clut).astype('>u2').tobytes()
    otab = np.round(np.linspace(0, 65535, n_out)).astype('>u2').tobytes()
    return head + ident + counts + in_tables + clut_b + otab * 3


def write_icc(path: str, description: str, lab: np.ndarray,
              input_table: np.ndarray, grid: int,
              copyright_: str = 'Generated by camicc') -> None:
    tags = [
        (b'desc', _desc_tag(description)),
        (b'cprt', _text_tag(copyright_)),
        (b'wtpt', _xyz_tag((0.9642, 1.0, 0.8249))),
        (b'A2B0', _mft2_tag(lab, input_table, grid)),
    ]
    tag_table = struct.pack('>I', len(tags))
    offset = 128 + 4 + 12 * len(tags)
    body = b''
    for sig, data in tags:
        tag_table += sig + struct.pack('>II', offset, len(data))
        pad = (4 - len(data) % 4) % 4
        body += data + b'\0' * pad
        offset += len(data) + pad

    size = 128 + 4 + 12 * len(tags) + len(body)
    header = struct.pack(
        '>I4sI4s4s4s', size, b'    ', 0x02400000, b'scnr', b'RGB ', b'Lab ')
    header += b'\0' * 12                        # creation date (unused)
    header += b'acsp' + b'\0' * 4               # signature + platform
    header += struct.pack('>III', 0, 0, 0)      # flags, manufacturer, model
    header += b'\0' * 8                         # attributes
    header += struct.pack('>I', 1)              # rendering intent: relative
    header += struct.pack('>3I', _s15f16(0.9642), _s15f16(1.0), _s15f16(0.8249))
    header += b'\0' * 48                        # creator + reserved
    assert len(header) == 128
    with open(path, 'wb') as f:
        f.write(header + tag_table + body)
